### ISSUE TITLE
with invalid parameter no error message displayed

### ISSUE THREAD

**Issue by rikribbers** [CenPC434/java-tools#1]
➜  target git:(master) java -jar en16931-xml-validator-0.2.0-SNAPSHOT-jar-with-dependencies.jar -xml ~/git/testset/SI-UBL-1.2/SI-UBL-INV-1.2-ok-minimal.xml -xslt
➜  target git:(master) cat log.txt
➜  target git:(master) 

Note that in the command the -xslt option is there but no value is provided, minor issue though as it works when a value is provided.

I was expecting a message saying the input is incorrect

**Comment by phax** [comment]
I improved parameter handling and it should do the trick now. Thanks for pointing this out
