### ISSUE TITLE
XML Validation

### ISSUE THREAD

**Issue by cryptolopes** [CenPC434/java-tools#3]
Hi,
Can you provide more information about the usage of validator?
It is possible to validate not only the core specification but also an extension by using the properly schema?

8a1843139a2874d9068ee389be91ff126eb629f5

**Comment by phax** [comment]
Sorry for the delay.
Basically the "Schematron validation tool" contained in here is a "generic" validator so it can be used generically.
The tools in this repository are not specific to any particular version of the EN 16931 validation artefacts.
Does that help you?
BR, Philip

**Comment by cryptolopes** [comment]
> Does that help you?

Thx for your feedback. It doesn't help but is a beginning.

**Comment by phax** [comment]
I suggest you look at https://github.com/phax/ph-bdve - it's a fully fledged engine with XSD and Schematron and out-of-the box EN 16031 support...

**Comment by cryptolopes** [comment]
> I suggest you look at https://github.com/phax/ph-bdve

Thx 🤗
